-- Crea la BD de cuentas: cuenta + movimiento
CREATE TABLE cuenta (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_cuenta   VARCHAR(255) NOT NULL UNIQUE,
    tipo_cuenta     VARCHAR(255),
    saldo_inicial   NUMERIC(38,2),
    estado          BOOLEAN,
    cliente_id      BIGINT NOT NULL
    -- NOTA: Sin FK a cliente, pues está en otra BD
);

CREATE TABLE movimiento (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_movimiento  VARCHAR(255),
    saldo            NUMERIC(38,2),
    valor            NUMERIC(38,2),
    fecha            TIMESTAMP(6),
    cuenta_id        BIGINT NOT NULL,
    CONSTRAINT fk_movimiento_cuenta
      FOREIGN KEY (cuenta_id)
      REFERENCES cuenta(id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);