version: '3.8'

services:
  db:
    image: postgres:15.3
    container_name: postgres-micro
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: micro
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init/BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "micro"]
      interval: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-micro
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      retries: 5

volumes:
  postgres_data:
