    create table cliente (
        estado boolean,
        id bigint not null,
        cliente_id varchar(255) not null unique,
        contrasena varchar(255),
        primary key (id)
    );

    create table persona (
        edad integer,
        id bigint generated by default as identity,
        direccion varchar(255),
        genero varchar(255),
        identificacion varchar(255),
        nombre varchar(255),
        telefono varchar(255),
        primary key (id)
    );

    alter table if exists cliente 
       add constraint FKkpvkbjg32bso6riqge70hwcel 
       foreign key (id) 
       references persona;
       
    create table cuenta (
        estado boolean,
        saldo_inicial numeric(38,2),
        id bigint generated by default as identity,
        numero_cuenta varchar(255) not null unique,
        tipo_cuenta varchar(255),
        primary key (id)
    );

    create table movimiento (
        saldo numeric(38,2),
        valor numeric(38,2),
        fecha timestamp(6),
        id bigint generated by default as identity,
        tipo_movimiento varchar(255),
        primary key (id)
    );
