    -- Creamos la tabla padre
    CREATE TABLE persona (
        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre         VARCHAR(255),
        identificacion VARCHAR(255),
        telefono       VARCHAR(255),
        direccion      VARCHAR(255),
        edad           INTEGER,
        genero         VARCHAR(255)
    );

    -- Creamos la tabla hija
    --    Usamos persona_id como PK y FK al mismo tiempo
    CREATE TABLE cliente (
        persona_id BIGINT NOT NULL,
        contrasena VARCHAR(255),
        estado     BOOLEAN,

        CONSTRAINT pk_cliente
          PRIMARY KEY (persona_id),

        CONSTRAINT fk_cliente_persona
          FOREIGN KEY (persona_id)
          REFERENCES persona(id)
          ON DELETE CASCADE
          ON UPDATE CASCADE
    );
       
    create table cuenta (
        id bigint generated by default as identity,
        primary key (id),
        numero_cuenta varchar(255) not null unique,
        tipo_cuenta varchar(255),
        saldo_inicial numeric(38,2),
        estado boolean
    );

    create table movimiento (
        id bigint generated by default as identity,
        primary key (id),
        tipo_movimiento varchar(255),
        saldo numeric(38,2),
        valor numeric(38,2),
        fecha timestamp(6)
    );
