spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/clientesdb
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # "validate" o "update" en desarrollo
    show-sql: true

    properties:
      "hibernate.format_sql": true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true # <-- importante
    baseline-version: 0 # (opcional, por defecto: 1)

server:
  port: 8081
  servlet:
    context-path: /api/v1
