spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/clientesdb
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # "validate" o "update" en desarrollo
    show-sql: true

    properties:
      "hibernate.format_sql": true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  flyway:
    enabled: false

server:
  port: 8081
  servlet:
    context-path: /api/v1

cuenta-service:
  url: http://localhost:8082

# SpringDoc (Swagger) — opcional, pero muy útil para probar tu API
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
