spring:
  application:
    name: cliente-service

  datasource:
    url: jdbc:postgresql://localhost:5434/clientesdb
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: pass

  flyway:
    enabled: false

server:
  port: 8081
  servlet:
    context-path: /api/v1

cuenta-service:
  url: http://localhost:8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Propiedades custom para RabbitConfig y ClienteServiceImpl
rabbitmq:
  exchange:
    cliente: cliente.exchange
  routingkey:
    cliente.created: cliente.created
