-- Crea la BD de clientes: persona + cliente
CREATE TABLE persona (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(255),
    identificacion VARCHAR(255),
    telefono       VARCHAR(255),
    direccion      VARCHAR(255),
    edad           INTEGER,
    genero         VARCHAR(255)
);

CREATE TABLE cliente (
    persona_id BIGINT NOT NULL,
    contrasena VARCHAR(255),
    estado     BOOLEAN,
    CONSTRAINT pk_cliente PRIMARY KEY (persona_id),
    CONSTRAINT fk_cliente_persona
      FOREIGN KEY (persona_id)
      REFERENCES persona(id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);