spring:
  application:
    name: cuenta-service

  datasource:
    url: jdbc:postgresql://localhost:5435/cuentasdb
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: pass

  flyway:
    enabled: false

server:
  port: 8082
  servlet:
    context-path: /api/v1

cliente-service:
  url: http://localhost:8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# ——————————————————————————————
# Propiedades custom para RabbitConfig y CuentaListener
rabbitmq:
  exchange:
    cliente: cliente.exchange
  queue:
    clienteCreated: cliente.created.queue
  routingkey:
    cliente:
      created: cliente.created
